FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY target/BankingJar.jar BankingJar.jar
ENTRYPOINT ["java", "-jar", "BankingJar.jar"]

#docker build -t BankingJar .
#docker run -it BankingJar

#docker run -it --entrypoint /bin/sh BankingJar
#java -jar BankingJar.jar